### ISSUE TITLE
cnschema 网站设计

### ISSUE THREAD

**Issue by lidingpku** [cnschema/cnschema#15]
目标： 给出cnschema第一期的网站设计，支持6月底网站上线

关键结果
1. wireframe， 网站页面交互逻辑设计（有几个网页，每个网页有哪些元素）
2. 网站页面渲染布局
3. 网站页面开发

详情

结合前期的讨论，我们形成了cnschema服务主站的MVP版本规划：初步版本希望能够保持与schema.org的连接，贡献整个社群。同时，针对中文服务的特质，加入了对更多schema来源的整合，优化搜索体验，提升已有schema的复用性。 有可能的话，开发的静态页面反向输出给schema.org作为官方静态页面

核心功能描述如下：
* 参考 schema.org 的概念页面和部分文档页面，保持基本布局
* 概念页面，增加中文翻译，中文化（原文对应，原始链接），wikification 对接wikipedia
* 概念搜索， autocomplete, search
* 技术文档，关于cnschema的编辑与使用
* 社区文档，关于cnschema社区的人员与协作
* 项目文档，关于cnschema的应用

**Comment by athoo** [comment]
0615

产品YPJ和设计XY进行了网站的第一次设计讨论，形成了网站基本结构的wireframe以及sitemap。
设计正在进行wireframe电子化和注解的工作，作为下一步low-fi设计的基础准备。

**Comment by lidingpku** [comment]
网站页面交互逻辑设计第一稿，征求意见中
[website-cnschema-20170620.pdf](https://github.com/cnschema/cnschema/files/1089246/website-cnschema-20170620.pdf)

**Comment by athoo** [comment]
页面内容包括：
1. 项目
    1. 项目列表
        1. 正在进行
        1. 计划中
        1. 已完成
    1. 已完成项目详情
        1. Markdown格式文章-供页面渲染使用
            1. 简介
            1. 作者
            1. 开发者
            1. 项目详情描述
1. 文档
    1. FAQ
    1. 使用手册
    1. Github页面链接
    1. 开发说明
1. 关于
    1. 理念
    1. 团队
    1. 招募
    1. 组织关联
    1. 联系方式
1. 实体
    1. 实体列表
        1. 链接
        1. 简介
    1. 实体详情页
        1. 属性说明
        1. 属性类别
        1. 属性描述
        1. 实体外链
        1. 属性外链（如果有的话）
        1. 实体简介

**Comment by lidingpku** [comment]
新的界面设计 https://drive.google.com/drive/folders/0B3oBHpezdq19dFN6aHVWQ09tNE0

**Comment by lidingpku** [comment]
例子
* http://cnschema.org/data/Person.json
* http://cnschema.org/Person
