### ISSUE TITLE
整理schema.org 3.2概念的语义，中文翻译，概念映射

### ISSUE THREAD

**Issue by lidingpku** [cnschema/cnschema#17]
目标： 整理schema.org 3.2概念的定义
* 对接，原始的英文定义
* 名称的中文翻译和中文解释 
* 概念链接 wikidata 和 wikipedia  （今后可以考虑增加 babelnet, 百度百科) 
* 输出基于JSON-LD规范的概念定义

思路
* 概念的理解最好能通过中文，英文的解释来明确。
* 如果是常见的概念，还应该可以找到相应的wikipedia网页解释
* 有些属性可以对应到wikidata （或者babelnet）这一类支持多语种的概念体系，减少多语种翻译成本

**Comment by lidingpku** [comment]
JSON-LD格式
![image](https://user-images.githubusercontent.com/638605/27223800-dfa4520c-5246-11e7-9b10-959d5ed0a9f9.png)

第一期的翻译结果
[schema-core-20170615.xlsx](https://github.com/cnschema/cnschema/files/1080547/schema-core-20170615.xlsx)

**Comment by lidingpku** [comment]
https://github.com/cnschema/cnschema/commit/a803013ebd0ea18d2ae46c9b1afee20233d4dbf3

**Comment by kn2322** [comment]
黄色的翻译还可改进。
[cns-core.xls.zip](https://github.com/cnschema/cnschema/files/1121749/cns-core.xls.zip)

**Comment by lidingpku** [comment]
https://github.com/cnschema/cnschema/commit/767133f74b2bcddd22cbddf21fb8bc6b1cf540c1
