### ISSUE TITLE
cnschema社区介绍文档

### ISSUE THREAD

**Issue by lidingpku** [cnschema/cnschema#19]
## 目标：形成关于社区的介绍
* 社区理念 https://schema.org/docs/about.html （改写）
* 联系方式， cnschema@openkg.cn

## 预期结果
https://github.com/cnschema/cnschema/wiki/%E5%85%B3%E4%BA%8ECNSchema

## 初步文字

CNSchema是由[OpenKG](http://OpenKG.CN)社区发起、管理和维护的开放知识图谱的Schema。这里的schema就是知识图谱中使用的类（Classes）、属性（Properties）和关系（Relations）的定义。CNSchema复用了[Schema.Org](http://Schema.Org)的Schema定义，并结合中文的特点进行了修订、增改和翻译。

CNSchema目前由一个OpenKG下属的工作委员会管理，通过[CNSchema GitHub](https://github.com/cnschema/cnschema)跟踪问题（Issues）。

CNSchema是完全开放的，有关它的讨论也是完全公开的。

CNSchema得到Schema.Org的负责人R.V. Guha和Dan Brickley的指导和支持。

**Comment by sunnaan** [comment]
丁老师，怎么加入社区？

**Comment by lidingpku** [comment]
https://github.com/cnschema/cnschema/wiki/%E5%85%B3%E4%BA%8EcnSchema
