### ISSUE TITLE
cnschema报告PPT

### ISSUE THREAD

**Issue by lidingpku** [cnschema/cnSchema#36]
[1708-cnschema-final.pdf](https://github.com/cnschema/cnschema/files/1259909/1708-cnschema-final.pdf)
presented  at ccks2017, 成都, 2017-08-29

```json
{
	"@id": "cnschema-slides-20170829",
	"@type": ["PresentationDigitalDocument"],
	"name": "cnSchema：开放中文知识图谱的schema",
	"description": "cnSchema是一个基于社区维护的开放的知识图谱Schema标准。cnSchema的词汇集包括了上千种概念分类(classes)、数据类型(data types)、属性(propertities)和关系(relations)等常用概念定义，以支持知识图谱数据的通用性、复用性和流动性。报告中也描述了我们遇到的挑战和工作方向，并且给出了案例分析和价值分析。现在任务的推进情况以及后续工作。感谢现有志愿者，招募新的志愿者。",
	"datePublished": "2017-08-29",
	"creator": [{
		"name": "丁力"
	}],
	"contentUrl": "https://github.com/cnschema/cnschema/files/1259909/1708-cnschema-final.pdf"
}
```

**Comment by lidingpku** [comment]
[1708-cnschema-0910-bit.pdf](https://github.com/cnschema/cnschema/files/1290241/1708-cnschema-0910-bit.pdf)
presented at 北理工知识图谱与问答系统交流会, 北京, 2017-09-10

{
	"@id": "cnschema-slides-20170829",
	"@type": ["PresentationDigitalDocument"],
	"name": "cnSchema：开放中文知识图谱的schema",
	"description": "cnSchema 面向中文信息处理，利用先进的知识图谱、自然语言处理和机器学习技术，融合结构化与文本数据，支持快速领域知识建模，支持跨数据源、跨领域、跨语言的开放数据自动化处理，为智能机器人、语义搜索、智能计算等新兴应用市场提供schema层面的支持与服务。",
	"datePublished": "2017-09-10",
	"creator": [{
		"name": "丁力"
	}],
	"contentUrl": "https://github.com/cnschema/cnschema/files/1290241/1708-cnschema-0910-bit.pdf"
}

**Comment by wencolani** [comment]
已将此页内容移至[wiki](https://github.com/cnschema/cnSchema/wiki#%E6%8A%A5%E5%91%8A)
