### ISSUE TITLE
请问在cnschema中如何找到籍贯、庙号这些属性名呢？

### ISSUE THREAD

**Issue by blake-li** [cnschema/cnSchema#46]

**Comment by lidingpku** [comment]
https://docs.google.com/spreadsheets/d/1b5DubotKUTU5tvT2pGXztwLpP63Xrc1le-VOuGKqbcw/edit#gid=653709023   cnSchema2.0 版开始增加新概念，可以看这个Excel  @blake-li

**Comment by wencolani** [comment]
可以通过[cnSchema网站演示](http://cnschema-vocabulary.openkg.cn/)对词汇表和属性表进行检索。
