### ISSUE TITLE
请问李老师，有cnschema使用手册吗？

### ISSUE THREAD

**Issue by pippon** [cnschema/cnSchema#48]
1、检索 2、下载，我感觉检索完就可以得到想要的信息了，还要下载什么内容呢？非常感谢！

**Comment by wencolani** [comment]
我们提供了cnSchema数据的检索和下载功能：
1. 检索：[cnSchema网站演示](http://cnschema-vocabulary.openkg.cn/)支持对词汇表和属性表的检索，检索可以为领域图谱schema构建提供参考；
2. 下载：cnSchema数据是开源的，使用者可以下载源数据进行使用。
