### ISSUE TITLE
怎么没有type/domain 和properties对应关系的文件？

### ISSUE THREAD

**Issue by yuqin11** [cnschema/cnSchema#49]
怎么没有type/domain 和properties对应关系的文件？我应当如何提取type和property的关系呢？

**Comment by dingmaotu** [comment]
在Excel文件里，有模版（template）页，就是定义类型和属性的对应关系的（绑定）。

**Comment by yuqin11** [comment]
看过了，两个excel文件只有type的解释以及propertis的解释，没有著名，每个type有哪些properties

**Comment by hellojet** [comment]
这里的没有，要看google docs上的那些文档，比如：
https://docs.google.com/spreadsheets/d/1b5DubotKUTU5tvT2pGXztwLpP63Xrc1le-VOuGKqbcw/edit#gid=0

**Comment by hellojet** [comment]
可以看下cnschema的kgtool库
