### ISSUE TITLE
cnSchema 网站上的词汇表无法加载

### ISSUE THREAD

**Issue by GUOXINTONG** [cnschema/cnSchema#54]
http://cnschema.org/_cns_vocab
这里的词汇表一直显示正在加载中，请问如何看到词汇表呢？

**Comment by hellojet** [comment]
clone下来后在vue-site中按照readme跑起来在本地可以看

**Comment by wencolani** [comment]
cnschema网站演示提供了词汇表展示，详见：
http://cnschema-vocabulary.openkg.cn/
