### ISSUE TITLE
概念：人物（Person）schema的整理

### ISSUE THREAD

**Issue by lidingpku** [cnschema/cnSchema#6]
本期目标：通过分析schema.org和Wikidata整理一组常用人物的属性

后续研究：
* 然后利用开放结构化数据Wikidata，百科等发现更多的人物实体，
* 利用人物实体发现更多的属性／关系，并予以融合
* 文本数据抽取人物以及属性／关系
* 利用人物实体，concept graph 研究实用的人物分类

**Comment by du00cs** [comment]
我原来来做这件事，可以指导一下我，我精力无限~

**Comment by zjumper** [comment]
如果我想要从Person类扩展一个子类出来，需要如何修改JSON-LD文件？发现JSON-LD文件里并没有类继承关系的定义描述？还有属性的domain，range定义也不知道在什么地方定义。
